# -*- coding: utf-8 -*-
"""Generador de Diccionario SSoT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148QT-4Ho07u194-SN3Aa27ajACZGBx6w
"""

import os

# Base de datos completa basada en el documento maestro de 34 dominios
data_dominios = [
    {
        "filename": "EstimacionRecursos.md",
        "tag": "#EstimaciónRecursos",
        "nombre": "Estimación de Recursos",
        "intro": "Competencia experta en la cuantificación de la variabilidad espacial y el riesgo geológico para la valorización de activos mineros.",
        "puntos": [
            "Análisis Exploratorio de Datos (EDA): Definición de unidades de estimación (dominios geológicos), análisis de continuidad espacial (variografía) y tratamiento de valores atípicos (capping/clamping).",
            "Estimación de Recursos: Ejecución de algoritmos de Kriging (Ordinario, Simple, de Indicadores) e Inverso a la distancia para variables continuas en corto plazo.",
            "Simulaciones Condicionales: Implementación de algoritmos (SGS, TB, etc.) para la cuantificación de la incertidumbre, análisis de riesgo y definición de mallas óptimas de perforación.",
            "Validación de Modelos: Técnicas de validación cruzada (Cross-Validation), Swath Plots y Shadow Estimation para auditoría interna de modelos de bloques."
        ]
    },
    {
        "filename": "OreControl.md",
        "tag": "#OreControl",
        "nombre": "Ore Control",
        "intro": "Ejecución de la geociencia operacional para la optimización de la selectividad, clasificación y destino del mineral en tiempo real, maximizando la recuperación metalúrgica y minimizando la dilución.",
        "puntos": [
            "Muestreo y QA/QC Operacional: Diseño y supervisión de protocolos de muestreo en pozos de tronadura (blast holes) y sondajes de corto plazo.",
            "Mapeo Geológico de Bancos: Ejecución de mapeo estructural, litológico y de alteración en frentes de carguío para actualización de modelos.",
            "Gestión de Destinos y Stocks: Determinación técnica de rutas de materiales basada en leyes de corte (cut-off grades) y contaminantes críticos.",
            "Reconciliación Operativa: Análisis de factores de reconciliación (Modelo vs. Mina vs. Planta) para identificar desviaciones.",
            "Geometalurgia de Corto Plazo: Monitoreo de variables que impactan el throughput y la molienda."
        ]
    },
    {
        "filename": "QAQC.md",
        "tag": "#QAQC",
        "nombre": "QA/QC",
        "intro": "Implementación y supervisión de protocolos sistemáticos para garantizar la trazabilidad, precisión y representatividad de la información geocientífica bajo estándares internacionales (NI 43-101, JORC).",
        "puntos": [
            "Protocolos de Inserción: Diseño y ejecución de programas mediante CRMs, Blancos, Duplicados (rechazo, pulpa, terreno) y Check Assays.",
            "Gestión de Errores y Sesgos: Análisis estadístico de precisión y exactitud mediante gráficos de control (Shewhart) y error relativo.",
            "Trazabilidad y Logística: Supervisión de la cadena de custodia desde el pozo hasta el análisis químico final.",
            "Auditoría de Bases de Datos: Validación de integridad lógica en SQL/Acquire detectando inconsistencias antes de la migración."
        ]
    },
    {
        "filename": "ExploracionMinera.md",
        "tag": "#ExploraciónMinera",
        "nombre": "Exploración Minera",
        "intro": "Ejecución y supervisión de programas de exploración geológica orientados al descubrimiento, delimitación y expansión de recursos minerales.",
        "puntos": [
            "Gestión de Campañas de Sondaje: Planificación de mallas (Diamantina/Aire Reverso) y supervisión de plataformas y recuperación.",
            "Logueo Geológico y Estructural: Registro sistemático de litología, alteración y mineralización transformando observaciones en datos vectoriales.",
            "Modelamiento Geológico: Integración de mapeo y geofísica para proponer modelos de génesis de yacimientos (Pórfidos, IOCG, Epitermales)."
        ]
    },
    {
        "filename": "AuditoriaTecnica.md",
        "tag": "#AuditoríaTécnica",
        "nombre": "Auditoría Técnica",
        "intro": "Evaluación sistemática e independiente de procesos, datos y modelos para garantizar la integridad técnica y mitigación de riesgos operativos/financieros.",
        "puntos": [
            "Validación de Integridad: Verificación de trazabilidad 'Mina a Modelo' y revisión de protocolos de cadena de custodia.",
            "Shadow Estimation: Construcción de modelos de bloques paralelos para detectar sesgos de interpolación o errores de selección de parámetros.",
            "Revisión Crítica de Parámetros: Evaluación de variografía, elipsoides de búsqueda y estrategias de octantes para evitar suavizamiento.",
            "Due Diligence Técnico: Identificación de 'Red Flags' en activos mineros y evaluación de reconciliación histórica.",
            "Certificación de Categorización: Auditoría de criterios de clasificación de recursos (Medidos, Indicados e Inferidos)."
        ]
    },
    {
        "filename": "DesarrolloNegocios.md",
        "tag": "#DesarrolloNegocios",
        "nombre": "Desarrollo de Negocios",
        "intro": "Identificación y captura de oportunidades estratégicas para la expansión de soluciones tecnológicas.",
        "puntos": [
            "Análisis de Mercado (TAM/SAM/SOM): Dimensionamiento del mercado potencial y segmentación de clientes estratégicos (Tier 1/2).",
            "Diseño de Modelos de Ingresos: Estructuración de modelos SaaS, licencias perpetuas o contratos basados en desempeño.",
            "Estrategia de Alianzas: Identificación de partners y canales de distribución para acelerar penetración."
        ]
    },
    {
        "filename": "GoToMarket.md",
        "tag": "#GoToMarket",
        "nombre": "Go-to-Market",
        "intro": "Diseño y ejecución de la hoja de ruta para el lanzamiento de nuevos productos o entrada a nuevos mercados mineros.",
        "puntos": [
            "Propuesta de Valor y Posicionamiento: Definición de diferenciadores técnicos y económicos (ROI) para resolver dolores específicos.",
            "Estrategia de Pricing: Configuración de precios basada en valor y análisis de competencia.",
            "Habilitación de Ventas: Creación de activos técnicos y comerciales (Business Cases, Whitepapers)."
        ]
    },
    {
        "filename": "AccountManagement.md",
        "tag": "#AccountManagement",
        "nombre": "Account Management",
        "intro": "Gestión estratégica de las relaciones con clientes existentes para maximizar el valor del ciclo de vida (LTV).",
        "puntos": [
            "Planificación Estratégica de Cuenta: Identificación de oportunidades de Upselling y Cross-selling.",
            "Gestión de Stakeholders: Navegación en estructuras organizacionales desde faena hasta C-Level.",
            "Monitoreo de Salud de Cuenta: Uso de métricas para prevenir el abandono (Churn)."
        ]
    },
    {
        "filename": "VentaConsultiva.md",
        "tag": "#VentaConsultiva",
        "nombre": "Venta Consultiva",
        "intro": "Proceso comercial basado en el diagnóstico profundo de problemas técnicos complejos para proponer soluciones a medida.",
        "puntos": [
            "Ingeniería de Ventas: Colaboración directa con I+D para adaptar el producto a restricciones reales de operación.",
            "Cuantificación de Beneficios: Traducción de métricas técnicas a beneficios financieros (ahorro OPEX).",
            "Manejo de Objeciones Técnicas: Resolución de dudas críticas sobre interoperabilidad, seguridad y TRL."
        ]
    },
    {
        "filename": "EscalamientoInternacional.md",
        "tag": "#EscalamientoInternacional",
        "nombre": "Escalamiento Internacional",
        "intro": "Adaptación y despliegue del modelo de negocio en múltiples jurisdicciones mineras globales.",
        "puntos": [
            "Localización de Producto: Ajuste de solución a normativas locales, idiomas y estándares técnicos regionales.",
            "Cumplimiento y Legal: Gestión de contratos internacionales, propiedad intelectual y regulaciones transfronterizas.",
            "Cultura de Negocios: Adaptación de tácticas de negociación a particularidades culturales regionales."
        ]
    },
    {
        "filename": "Fidelizacion.md",
        "tag": "#Fidelización",
        "nombre": "Fidelización",
        "intro": "Estrategias orientadas a la retención de clientes mediante la garantía de que la tecnología sea un activo indispensable.",
        "puntos": [
            "Customer Success Técnico: Acompañamiento post-venta para asegurar implementación y uso correcto.",
            "Programas de Adopción: Entrenamiento continuo y feedback loops para evolucionar el producto.",
            "Métricas de Retención: Análisis de tasas de renovación y satisfacción (NPS)."
        ]
    },
    {
        "filename": "ValorizacionTecnologica.md",
        "tag": "#ValorizaciónTecnológica",
        "nombre": "Valorización Tecnológica",
        "intro": "Análisis de los fundamentos financieros que determinan la rentabilidad y el valor económico de una solución tecnológica.",
        "puntos": [
            "Cálculo de LTV & CAC: Determinación del valor de vida del cliente frente al costo de adquisición.",
            "Modelamiento de ROI: Construcción de modelos financieros para demostrar el ahorro o ganancia de la minera.",
            "Valorización de Activos Intangibles: Estimación del valor de la Propiedad Intelectual (IP) y algoritmos propios."
        ]
    },
    {
        "filename": "MaduracionTecnologica.md",
        "tag": "#MaduraciónTecnológica",
        "nombre": "Maduración Tecnológica",
        "intro": "Gestión sistemática del ciclo de maduración (Deep-Tech) desde laboratorio hasta implementación industrial (TRL).",
        "puntos": [
            "Gestión de Niveles TRL: Monitoreo de hitos desde TRL 3-4 hasta la validación operativa final TRL 8-9.",
            "Diseño de Pilotaje: Estructuración de protocolos en terreno bajo restricciones reales (polvo, vibración, conectividad).",
            "Identificación de Gaps: Análisis de riesgos técnicos previos al escalamiento.",
            "Certificación de Industria: Aseguramiento de estándares de interoperabilidad y ciberseguridad corporativa.",
            "Transferencia Tecnológica: Liderazgo en la entrega de solución desde I+D hacia Operaciones."
        ]
    },
    {
        "filename": "CapitalAllocation.md",
        "tag": "#CapitalAllocation",
        "nombre": "Capital Allocation",
        "intro": "Estrategia de distribución eficiente de recursos financieros para maximizar el ROI en activos de I+D e innovación.",
        "puntos": [
            "Ingeniería de Fundraising: Captura de capital no diluyente (ANID/CORFO) alineando hitos con requisitos financieros.",
            "Optimización de Presupuesto: Gestión del 'Burn Rate' equilibrando velocidad de desarrollo y sostenibilidad.",
            "Análisis de Oportunidad: Evaluación de inversión en desarrollo vs. validación en terreno para avanzar TRL.",
            "Justificación y Compliance: Aseguramiento de cumplimiento de auditorías y estándares de transparencia.",
            "Valorización de Resultados: Traducción de hitos técnicos en valor económico para la compañía."
        ]
    },
    {
        "filename": "TechAdoption.md",
        "tag": "#TechAdoption",
        "nombre": "Tech Adoption",
        "intro": "Estrategias orientadas a vencer la resistencia cultural en la operación minera garantizando el uso efectivo.",
        "puntos": [
            "Diseño Centrado en el Usuario (UCD): Adaptación de interfaces a la realidad ergonómica y cognitiva del operador.",
            "Programas de Evangelización: Formación para empoderar a usuarios finales como promotores.",
            "Análisis de Barreras: Identificación de factores humanos o técnicos que impiden la integración diaria.",
            "Monitoreo de Implementación: Uso de métricas de uso real para corregir fricciones proactivamente."
        ]
    },
    {
        "filename": "RemocionDeBloqueos.md",
        "tag": "#RemociónDeBloqueos",
        "nombre": "Remoción de Bloqueos",
        "intro": "Identificación proactiva y resolución de impedimentos técnicos o burocráticos en proyectos de alta incertidumbre.",
        "puntos": [
            "Detección de Cuellos de Botella: Monitoreo de permisos y latencia de datos para evitar impactos en cronograma.",
            "Gestión de Recursos Críticos: Negociación para asegurar tiempo de expertos e infraestructura compartida.",
            "Simplificación Lean: Eliminación de pasos que no agregan valor en la validación técnica.",
            "Escalamiento Estratégico: Elevación de conflictos críticos a niveles C-Level con análisis riesgo/beneficio."
        ]
    },
    {
        "filename": "StakeholderManagement.md",
        "tag": "#StakeholderManagement",
        "nombre": "Stakeholder Management",
        "intro": "Orquestación de intereses de todos los actores asegurando alineación entre visión de producto y metas de área.",
        "puntos": [
            "Mapa de Influencia: Identificación de promotores y detractores en corporaciones Tier 1.",
            "Negociación Win-Win: Alineación de innovación con KPIs de producción y seguridad operacional.",
            "Reporting RAG: Comunicación transparente sobre riesgos y avances basada en datos."
        ]
    },
    {
        "filename": "TechnicalTranslation.md",
        "tag": "#TechnicalTranslation",
        "nombre": "Technical Translation",
        "intro": "Capacidad de actuar como nodo traductor entre la geología operativa y el desarrollo de sistemas.",
        "puntos": [
            "Arquitectura de Requerimientos: Traducción de 'dolores' del geólogo en User Stories técnicas.",
            "Validación Geocientífica: Supervisión de que algoritmos respeten la geoestadística y restricciones físicas.",
            "Data Literacy: Capacitación de equipos de campo en arquitecturas de datos e interoperabilidad."
        ]
    },
    {
        "filename": "Lean.md",
        "tag": "#Lean",
        "nombre": "Lean",
        "intro": "Aplicación de principios de mejora continua para maximizar la entrega de valor en entornos de alta variabilidad.",
        "puntos": [
            "Gestión Visual (Kanban): Uso de tableros para visibilizar estado y evitar sobrecarga (WIP).",
            "Métricas de Eficiencia: Seguimiento de Lead Time y Cycle Time para predecir entregas.",
            "Cultura de Retrospectiva: Implementación de ciclos de aprendizaje después de cada pilotaje o MVP."
        ]
    },
    {
        "filename": "RoadmapProducto.md",
        "tag": "#RoadmapProducto",
        "nombre": "Roadmap de Producto",
        "intro": "Orquestación estratégica del ciclo de vida evolutivo de soluciones, equilibrando visión y ejecución táctica.",
        "puntos": [
            "Visión Estratégica: Definición del 'North Star' alineado con tendencias (Autonomía, Digitalización).",
            "Priorización Multivariable: Uso de frameworks (RICE, Kano) para toma de decisiones sobre backlog.",
            "Gestión de Dependencias: Identificación de rutas críticas entre hardware, software y validación química.",
            "Comunicación de Hitos: Traducción de estado técnico en lenguaje de valor para directorios."
        ]
    },
    {
        "filename": "ID.md",
        "tag": "#I+D",
        "nombre": "I+D",
        "intro": "Gestión de la frontera del conocimiento transformando ciencia pura en activos tecnológicos explotables.",
        "puntos": [
            "Vigilancia Tecnológica: Monitoreo de publicaciones y patentes para anticipar disrupciones.",
            "Gestión de IP: Identificación de algoritmos únicos susceptibles de protección (patentes).",
            "Diseño Experimental: Estructuración de pruebas con rigor estadístico para validar nuevas teorías.",
            "Mitigación de Riesgo: Evaluación constante de viabilidad técnica para evitar gasto hundido."
        ]
    },
    {
        "filename": "ProductDiscovery.md",
        "tag": "#ProductDiscovery",
        "nombre": "Product Discovery",
        "intro": "Metodología continua de exploración para asegurar un 'Product-Market Fit' real en minería.",
        "puntos": [
            "User Research: Entrevistas en profundidad y observación etnográfica en faena.",
            "Problem Framing: Separación del 'síntoma' reportado de la causa raíz técnica.",
            "Prototipado: Creación de maquetas funcionales para validar flujos de interacción.",
            "Validación de Usabilidad: Pruebas de campo para medir curva de aprendizaje en estrés operativo."
        ]
    },
    {
        "filename": "MVP.md",
        "tag": "#MVP",
        "nombre": "MVP",
        "intro": "Estrategia de empaquetamiento funcional mínimo para validar propuesta de valor con menor uso de recursos.",
        "puntos": [
            "Identificación de Core Value: Determinación de la funcionalidad mínima crítica.",
            "Arquitectura de Lanzamiento: Diseño de infraestructura básica para soporte de piloto controlado.",
            "Métricas de Éxito: Definición de KPIs para decidir escalamiento post-piloto.",
            "Gestión de Deuda Técnica: Decisión estratégica sobre optimizaciones post-validación."
        ]
    },
    {
        "filename": "VinculacionEcosistemica.md",
        "tag": "#VinculaciónEcosistémica",
        "nombre": "Vinculación Ecosistémica",
        "intro": "Articulación entre empresa, academia, gobierno y proveedores para potenciar innovación.",
        "puntos": [
            "Gestión de Partners: Colaboración con universidades para integrar ciencia de vanguardia.",
            "Networking: Representación de la compañía en asociaciones gremiales y mesas técnicas.",
            "Open Innovation: Scouting de tecnologías externas para acelerar desarrollo interno."
        ]
    },
    {
        "filename": "ArquitecturaDeRequerimientos.md",
        "tag": "#ArquitecturaDeRequerimientos",
        "nombre": "Arquitectura de Requerimientos",
        "intro": "Diseño de especificaciones técnicas y funcionales asegurando coherencia entre necesidad y factibilidad.",
        "puntos": [
            "Elicitación de Requisitos: Extracción de necesidades críticas mediante descubrimiento técnico.",
            "Modelamiento de Procesos: Creación de diagramas de flujo y casos de uso para equipos dev.",
            "Gestión de Trazabilidad: Aseguramiento de que cada feature responda a un requerimiento validado.",
            "Análisis de Impacto: Evaluación de cómo cambios afectan arquitectura y operación."
        ]
    },
    {
        "filename": "ComplianceEndToEnd.md",
        "tag": "#ComplianceEndToEnd",
        "nombre": "Compliance End-to-End",
        "intro": "Aseguramiento de cumplimiento de estándares legales, técnicos y de seguridad exigidos por mineras Tier 1.",
        "puntos": [
            "Estándares Corporativos: Alineación con ciberseguridad, ética de datos y protocolos HSE.",
            "Auditoría de Procesos: Controles internos para garantizar seguimiento de procedimientos.",
            "Gobernanza de Datos: Aseguramiento de propiedad, privacidad y calidad de información.",
            "Gestión de SLAs: Monitoreo de niveles de servicio y compromisos contractuales."
        ]
    },
    {
        "filename": "MetricaDeFlujo.md",
        "tag": "#MétricaDeFlujo",
        "nombre": "Métricas de Flujo",
        "intro": "Aplicación de indicadores de agilidad para medir eficiencia y velocidad del despliegue.",
        "puntos": [
            "Lead Time & Cycle Time: Seguimiento desde solicitud hasta entrega en producción.",
            "Throughput: Medición del volumen de ítems completados por unidad de tiempo.",
            "WIP Management: Gestión de carga activa para evitar cuellos de botella.",
            "Cumulative Flow (CFD): Identificación visual de inestabilidades en el sistema."
        ]
    },
    {
        "filename": "ReportingRAG.md",
        "tag": "#ReportingRAG",
        "nombre": "Reporting RAG",
        "intro": "Sistema de comunicación de salud del proyecto (Red-Amber-Green) para visibilidad de riesgos.",
        "puntos": [
            "Semáforo de Gestión: Clasificación de hitos por presupuesto, tiempo y calidad.",
            "Análisis Causa Raíz: Explicación técnica de desviaciones y estados críticos.",
            "Planes de Mitigación: Propuesta de acciones para devolver proyecto a estado verde.",
            "Síntesis Ejecutiva: Traducción de métricas complejas en insights para C-Level."
        ]
    },
    {
        "filename": "TPM.md",
        "tag": "#TPM",
        "nombre": "Technical Project Management",
        "intro": "Liderazgo integral de proyectos que requieren entender arquitectura de sistemas y geociencia.",
        "puntos": [
            "Orquestación Multidisciplinaria: Coordinación entre geólogos, dev y científicos de datos.",
            "Gestión de Ruta Crítica: Optimización de recursos expertos en tareas determinantes.",
            "QA Técnico: Supervisión de robustez para condiciones mineras extremas.",
            "Gestión de Deuda Técnica: Decisión estratégica velocidad vs. perfección."
        ]
    },
    {
        "filename": "FondosPublicos.md",
        "tag": "#FondosPúblicos",
        "nombre": "Fondos Públicos",
        "intro": "Estrategia para captura de capital estatal/multilateral destinado a la innovación.",
        "puntos": [
            "Ingeniería de Formulación: Estructuración de propuestas para ANID/CORFO.",
            "Justificación de Impacto: Traducción de valor técnico en métricas de productividad país.",
            "Gestión de Rendición: Ejecución rigurosa de auditorías de gasto y cumplimiento de hitos.",
            "Relación Institucional: Navegación en el ecosistema para influir en líneas de financiamiento."
        ]
    },
    {
        "filename": "GobernanzaProyectos.md",
        "tag": "#GobernanzaProyectos",
        "nombre": "Gobernanza de Proyectos",
        "intro": "Implementación de marcos normativos y estructuras de decisión para proyectos de alta incertidumbre.",
        "puntos": [
            "Diseño de Steering Committees: Creación de instancias de gobernanza con stakeholders clave.",
            "Matriz RACI: Definición de roles y niveles de autoridad en equipos multidisciplinarios.",
            "Gobernanza de Datos: Protocolos de seguridad y derechos de información con mineras Tier 1.",
            "Change Control: Procesos formales para aprobar modificaciones de alcance."
        ]
    },
    {
        "filename": "InteroperabilidadTecnica.md",
        "tag": "#InteroperabilidadTécnica",
        "nombre": "Interoperabilidad Técnica",
        "intro": "Diseño de soluciones que operen fluidamente en el ecosistema digital minero existente.",
        "puntos": [
            "Integración Legacy: Conexores para interactuar con SAP, Vulcan o Datamine.",
            "Estandarización de Datos: Formatos JSON/SQL para flujo sin fricción hacia planta.",
            "Arquitectura de Microservicios: Gestión de componentes modulares escalables.",
            "Seguridad Industrial: Cumplimiento de normativas de protección de infraestructura crítica."
        ]
    },
    {
        "filename": "MinaToSoftware.md",
        "tag": "#MinaToSoftware",
        "nombre": "Mina-to-Software",
        "intro": "Codificación de la realidad física y operativa de la minería en algoritmos lógicos funcionales.",
        "puntos": [
            "Reglas de Negocio Operativas: Automatización de procesos manuales de logueo o selección.",
            "UX para Entornos Extremos: Interfaces para tablets con baja conectividad y uso de guantes.",
            "Digital Twin: Representaciones digitales de activos físicos reaccionando en tiempo real."
        ]
    },
    {
        "filename": "UserEnablement.md",
        "tag": "#UserEnablement",
        "nombre": "User Enablement",
        "intro": "Garantía de autonomía y conocimiento del usuario para generar valor real con la herramienta.",
        "puntos": [
            "Adoption Journeys: Mapeo de experiencia desde el contacto inicial hasta el uso experto.",
            "Sandboxes de Entrenamiento: Entornos de prueba para experimentación sin riesgo operacional.",
            "Learning Assets: Producción de guías, videos y documentación viva del producto.",
            "Soporte Experto: Mentoría técnica sobre el propósito y valor de la herramienta."
        ]
    }
]

def crear_archivos():
    target_dir = "dominios"
    if not os.path.exists(target_dir):
        os.makedirs(target_dir)
        print(f"📁 Carpeta '{target_dir}' creada.")

    template = """---
ID: "{tag}"
Nombre: "{nombre}"
---

# {tag}

## 💎 Valor Estratégico
{intro}

## 🛠️ Ejes de Acción
{puntos_md}

## 📂 Evidencia en Proyectos
* [[PROY-AU] Evaluación de Riesgo de Plan Minero (Oro)](../proyectos/PROY-AU.md)

---
[⬅️ Volver al Diccionario](./README.md)
"""

    for d in data_dominios:
        puntos_md = "\n".join([f"* {p}" for p in d["puntos"]])
        content = template.format(
            tag=d["tag"],
            nombre=d["nombre"],
            intro=d["intro"],
            puntos_md=puntos_md
        )

        filepath = os.path.join(target_dir, d["filename"])
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✅ Generado: {d['filename']}")

    print(f"\n🚀 ¡Éxito! Se han generado {len(data_dominios)} archivos en la carpeta '{target_dir}'.")

if __name__ == "__main__":
    crear_archivos()